name: raptitapp2025
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family: PretendardJP
      fonts:
        - asset: assets/fonts/PretendardJP/PretendardJP-Thin.ttf
          weight: 100
        - asset: assets/fonts/PretendardJP/PretendardJP-Light.ttf
          weight: 300
        - asset: assets/fonts/PretendardJP/PretendardJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/PretendardJP/PretendardJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/PretendardJP/PretendardJP-Black.ttf
          weight: 900